### ISSUE TITLE
Fatal error: Call to a member function scaffoldSearchField() on null

### ISSUE THREAD

**Issue by barry-bookinglive** [nglasl/silverstripe-fusion#1]
Hi I've tried the most simple case I could... one DataObject in one ModelAdmin and after dev build and visiting the Admin I get the following error...

Fatal error: Call to a member function scaffoldSearchField() on null in C:\xampp\htdocs\ssv3110\framework\model\DataObject.php on line 1977

**Comment by nglasl** [comment]
Hey there. Would you happen to have any further information on this one? This single DataObject, what type of DataObject was it? The error is coming from framework, so it's possible that the error isn't related to the fusion module.

**Comment by barry-bookinglive** [comment]
It's as basic an example as you can get... this is laid onto ssv3.1.13 and reproduces the error

---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
SSViewer:
  theme: 'simple'
MyObject:
  extensions:
    - 'TaggingExtension'

class MyAdmin extends ModelAdmin {
	static $managed_models = array('MyObject');
	static $url_segment = 'myadmin';
	static $menu_title = 'My Admin';
	static $menu_priority = 0;
}

class MyObject extends DataObject {
	static $db = array(
		"Name"			=> "Varchar",
	);
}

**Comment by nglasl** [comment]
Thanks for supplying your code, exactly what I was after!

Okay, so it looks like it's an issue with the way that searchable fields are determined when they don't reference an existing field, as it's expecting a **Title**. I've just made some adjustments which look to correct the issue and make things a little more robust, and I'll be pushing out a new release tag soon :)
