### ISSUE TITLE
Column 'ID' in where clause is ambiguous

### ISSUE THREAD

**Issue by Neumes** [nglasl/silverstripe-fusion#10]
I'm manually writing an extended TaxonomyTerm DataObject for a project and this error was being thrown. It was triggered specifically on line 57 of FusionExtension and I was able to fix this locally by changing :
`'ID != ?' => $this->owner->ID,`
to
`$class.'.ID != ?' => $this->owner->ID,`
Which I'm unsure if it would break anything else along the way.

It's worth noting the extended TaxonomyTerm DataObject had no defined database fields.

This was occurring during writing the tag for the first time :

```
$extTerm = ExtTaxonomyTerm::create();
$extTerm->Name = "TextVal";
$extTerm->write();
```

**Comment by nglasl** [comment]
Thanks for picking this up, a fix will be pushed soon.
